scss_files: 'src/styles/*.scss'

# default config from https://github.com/causes/scss-lint/blob/master/config/default.yml
linters:
  BorderZero:
    enabled: true

  CapitalizationInSelector:
    enabled: true

  ColorKeyword:
    enabled: false

  ColorVariable:
    enabled: false

  Comment:
    enabled: false

  DebugStatement:
    enabled: true

  DeclarationOrder:
    enabled: true

  DuplicateProperty:
    enabled: true

  EmptyLineBetweenBlocks:
    enabled: true
    ignore_single_line_blocks: true

  EmptyRule:
    enabled: true

  FinalNewline:
    enabled: false
    present: false

  HexLength:
    enabled: false

  HexFormat:
    enabled: true

  IdSelector:
    enabled: false

  IdWithExtraneousSelector:
    enabled: true

  ImportantRule:
    enabled: true

  Indentation:
    enabled: true
    width: 4

  LeadingZero:
    enabled: true
    style: exclude_zero

  NameFormat:
    enabled: true
    convention: hyphenated_lowercase # or 'BEM', or a regex pattern

  SelectorFormat:
    enabled: true
    convention: hyphenated_lowercase # or 'BEM', or a regex pattern
    ignored_names: ['ng\:cloak', 'new_window']

  PlaceholderInExtend:
    enabled: false

  PropertySortOrder:
    enabled: false

  PropertySpelling:
    enabled: true
    extra_properties: []

  SelectorDepth:
    enabled: true
    max_depth: 3

  NestingDepth:
    enabled: true
    max_depth: 6

  SelectorFormat:
    enabled: false

  Shorthand:
    enabled: true

  SingleLinePerSelector:
    enabled: true

  SpaceAfterComma:
    enabled: true

  SpaceAfterPropertyColon:
    enabled: true

  SpaceAfterPropertyName:
    enabled: true

  SpaceBeforeBrace:
    enabled: true
    allow_single_line_padding: false

  SpaceBetweenParens:
    enabled: true
    spaces: 0

  StringQuotes:
    enabled: true
    style: single_quotes

  TrailingSemicolonAfterPropertyValue:
    enabled: true

  UnnecessaryMantissa:
    enabled: true

  UrlFormat:
    enabled: false

  UrlQuotes:
    enabled: true

  ZeroUnit:
    enabled: true

  Compass::*:
    enabled: false

  HexValidation:
    enabled: true

  VendorPrefix:
    enabled: false

  QualifyingElement:
    enabled: false
